### ISSUE TITLE
Configuration Enhancement

### ISSUE THREAD

**Issue by lapplislazuli** [Tritlo/Endemic#18]
We should improve the Configuration with having a configuration file, and an overwriting with console params

- [x] Make Central Configuration-Data in Code 
- [x] Add Configuration File Support
- [ ] Add Commandline Support
- [x] Add Overwrite

This is somewhat a pre-requisite for #17

**Comment by Tritlo** [comment]
We've got JSON configuration now, and you can even specify it on the command line as well, i.e.:

`cabal run endemic -- tests/ThreeFixes.hs --config='{ "search_algorithm": {"tag": "Genetic", "contents":{ "population_size": 200}}, "log_level": "INFO"}'`

It also supports files:

`cabal run endemic -- tests/ThreeFixes.hs --config=config.json`

I'm thinking that should be enough? I'm not entirely sure how we'll nest the command line arguments otherwise. So I'm thinking:
we remove the nested CLI arguments (i.e. keeping "log_level" and "log_loc", etc.), but all nested configuration must happen by using the `--config` flag. I'll add an `--override` flag, so if you're reading configuration from a file, you can manually override that way. So in total the flags will be:
+ `--debug` for dumping a bunch of debug stats
+ `--log-loc` to add location info to log messages
+ `--seed` to set the random seed
+ `--log-level` to change the log level
+ `--config` to set the base configuration
+ `--override` to override the base configuration

`debug`, `log-loc`, `log-level` and `seed`  can be set in the `config` as well. Finally a "non" flag will be the list of targets (only one target supported ATM)

What do you think @lapplislazuli?
